document.write( '  <div class=\"mdl-layout mdl-js-layout mdl-layout--fixed-header\">\n' );
document.write( '\n' );
document.write( '      <div class=\"android-header mdl-layout__header mdl-layout__header--waterfall\">\n' );
document.write( '        <div class=\"mdl-layout__header-row\">\n' );
document.write( '          <span class=\"android-title mdl-layout-title\">\n' );
document.write( '            <a href=\"../homepage/index.html\"><img class=\"android-logo-image\" src=\"../images/logo.png\"></a>\n' );
document.write( '          </span>\n' );
document.write( '          <!-- Add spacer, to align navigation to the right in desktop -->\n' );
document.write( '          <div class=\"android-header-spacer mdl-layout-spacer\"></div>\n' );
document.write( '          <div class=\"android-search-box mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right mdl-textfield--full-width\">\n' );
document.write( '            <label class=\"mdl-button mdl-js-button mdl-button--icon\" for=\"search-field\">\n' );
document.write( '              <a href=\"../search/index.html\"><i class=\"material-icons\">search</i></a>\n' );
document.write( '            </label>\n' );
document.write( '            <div class=\"mdl-textfield__expandable-holder\">\n' );
document.write( '              <input class=\"mdl-textfield__input\" type=\"text\" id=\"search-field\">\n' );
document.write( '            </div>\n' );
document.write( '          </div>\n' );
document.write( '          <!-- Navigation -->\n' );
document.write( '          <div class=\"android-navigation-container\">\n' );
document.write( '            <nav class=\"android-navigation mdl-navigation\">\n' );
document.write( '              <a class=\"mdl-navigation__link mdl-typography--text-uppercase\" href=\"\">Windows</a>\n' );
document.write( '              <a class=\"mdl-navigation__link mdl-typography--text-uppercase\" href=\"../linux/index.html\">Linux</a>\n' );
document.write( '              <a class=\"mdl-navigation__link mdl-typography--text-uppercase\" href=\"../raspberrypi/index.html\">Raspberry Pi</a>\n' );
document.write( '              <a class=\"mdl-navigation__link mdl-typography--text-uppercase\" href=\"\">Misc</a>\n' );
document.write( '            </nav>\n' );
document.write( '          </div>\n' );
document.write( '          <span class=\"android-mobile-title mdl-layout-title\">\n' );
document.write( '            <a href=\"../homepage/index.html\"><img class=\"android-logo-image\" src=\"../images/logo.png\"></a>\n' );
document.write( '          </span>\n' );
document.write( '          <button class=\"android-more-button mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect\" id=\"more-button\">\n' );
document.write( '            <i class=\"material-icons\">more_vert</i>\n' );
document.write( '          </button>\n' );
document.write( '          <ul class=\"mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect\" for=\"more-button\">\n' );
document.write( '            <li class=\"mdl-menu__item\">IT Support</li>\n' );
document.write( '            <li class=\"mdl-menu__item\">Donate</li>\n' );
document.write( '            <li class=\"mdl-menu__item\">About</li>\n' );
document.write( '          </ul>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '\n' );
document.write( '      <div class=\"android-drawer mdl-layout__drawer\">\n' );
document.write( '        <span class=\"mdl-layout-title\">\n' );
document.write( '          <img class=\"android-logo-image\" src=\"../images/logo-white.png\">\n' );
document.write( '        </span>\n' );
document.write( '        <nav class=\"mdl-navigation\">\n' );
document.write( '          <a class=\"mdl-navigation__link\" href=\"\">Windows</a>\n' );
document.write( '          <a class=\"mdl-navigation__link\" href=\"../linux/index.html\">Linux</a>\n' );
document.write( '          <a class=\"mdl-navigation__link\" href=\"../raspberrypi/index.html\">Raspberry Pi</a>\n' );
document.write( '          <a class=\"mdl-navigation__link\" href=\"\">Misc</a>\n' );
document.write( '          <div class=\"android-drawer-separator\"></div>\n' );
document.write( '          <span class=\"mdl-navigation__link\" href=\"\">More</span>\n' );
document.write( '          <a class=\"mdl-navigation__link\" href=\"\">IT Support</a>\n' );
document.write( '          <a class=\"mdl-navigation__link\" href=\"\">Donate</a>\n' );
document.write( '          <a class=\"mdl-navigation__link\" href=\"\">About</a>\n' );
document.write( '        </nav>\n' );
document.write( '      </div>\n' );
